parser: '@typescript-eslint/parser'
extends:
  - 'plugin:@typescript-eslint/recommended'
parserOptions:
  ecmaVersion: 2018
  project: ./tsconfig.json
plugins:
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - always-multiline
  '@typescript-eslint/camelcase':
    - off
  '@typescript-eslint/explicit-function-return-type':
    - off
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: 'none'
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-unused-vars':
    - off
  '@typescript-eslint/semi':
    - error
    - never
