parser: '@typescript-eslint/parser'
extends:
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2018
  emitDecoratorMetadata: true
plugins:
  - import
  - '@typescript-eslint'
rules:
  comma-dangle:
    - error
    - always-multiline
  eol-last:
    - error
  import/newline-after-import:
    - error
    - count: 1
  import/order:
    - error
    - alphabetize:
        caseInsensitive: true
        order: asc
      groups:
        - builtin
        - external
        - [parent, sibling, index]
      newlines-between: never
  no-trailing-spaces:
    - error
  object-curly-spacing:
    - error
    - always
  prefer-const:
    - error
    - destructuring: 'all'
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
    - avoidEscape: true
  space-infix-ops:
    - error
  space-unary-ops:
    - error
    - overrides:
        '!': true
  '@typescript-eslint/consistent-type-imports':
    - error
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: 'none'
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-inferrable-types':
    - off
  '@typescript-eslint/no-unused-vars':
    - off
  '@typescript-eslint/semi':
    - error
    - never
